@echo off
ren output\outdat\sna\48k\app\*.SNA *.sna
ren output\outdat\sna\48k\arcade\*.SNA *.sna
ren output\outdat\sna\48k\action\*.SNA *.sna
ren output\outdat\sna\48k\board\*.SNA *.sna
ren output\outdat\sna\48k\card\*.SNA *.sna
ren output\outdat\sna\48k\chess\*.SNA *.sna
ren output\outdat\sna\48k\combat\*.SNA *.sna
ren output\outdat\sna\48k\dungeon\*.SNA *.sna
ren output\outdat\sna\48k\gambling\*.SNA *.sna
ren output\outdat\sna\48k\maze\*.SNA *.sna
ren output\outdat\sna\48k\mouse\*.SNA *.sna
ren output\outdat\sna\48k\pinball\*.SNA *.sna
ren output\outdat\sna\48k\platform\*.SNA *.sna
ren output\outdat\sna\48k\pong\*.SNA *.sna
ren output\outdat\sna\48k\puzzle\*.SNA *.sna
ren output\outdat\sna\48k\quiz\*.SNA *.sna
ren output\outdat\sna\48k\race\*.SNA *.sna
ren output\outdat\sna\48k\rpg\*.SNA *.sna
ren output\outdat\sna\48k\scene\*.SNA *.sna
ren output\outdat\sna\48k\school\*.SNA *.sna
ren output\outdat\sna\48k\shoot\*.SNA *.sna
ren output\outdat\sna\48k\simul\*.SNA *.sna
ren output\outdat\sna\48k\sport\*.SNA *.sna
ren output\outdat\sna\48k\strategy\*.SNA *.sna
ren output\outdat\sna\48k\tactical\*.SNA *.sna
ren output\outdat\sna\48k\venture\*.SNA *.sna
ren output\outdat\sna\48k\war\*.SNA *.sna